// YouTube AI & Bot Detector — Content Script v2

(function () {
  'use strict';

  // ── Attribute used to mark every processed element ────────────────────────
  const ATTR = 'data-ytabd';

  const REEL_SEL = `ytd-reel-video-renderer:not([${ATTR}])`;
  const COMMENT_SEL = [
    `ytd-comment-renderer:not([${ATTR}])`,
    `ytd-comment-view-model:not([${ATTR}])`,
  ].join(',');

  // ── BOT patterns — one match flags a comment as BOT ──────────────────────
  const BOT_PATTERNS = [
    /\+\s*\d[\d\s\-\.\(\)]{8,}\d/,
    /(?:whatsapp|watsapp|wa\.me)\s*[:\-]?\s*\+?[\d\s\-\.\(\)]{8,}/i,
    /(?:telegram|t\.me)\s*[:\-]?\s*@?[\w]{4,}/i,
    /(?:bitcoin|btc|crypto|invest(?:ment)?|forex|trading)\b.{0,50}(?:\$\s*\d|\d+\s*%\s*(?:profit|return|daily|weekly))/i,
    /(?:earn|make|get)\s+\$[\d,]+\s+(?:daily|weekly|monthly|per\s+(?:day|week))/i,
    /I\s+(?:made|earned|got)\s+\$[\d,]+\s+(?:in|within)\s+\d+\s+(?:day|week|hour)/i,
    /(?:congratulations?|you(?:'ve| have) been (?:selected|chosen))\b.{0,80}(?:prize|gift|reward|winner|claim)/i,
    /(?:sub(?:scribe)?|follow).{0,15}(?:back|4|for).{0,15}(?:sub(?:scribe)?|follow)/i,
    /(?:bit\.ly|tinyurl\.com|rb\.gy|cutt\.ly|ow\.ly)\//i,
    /(.)\1{7,}/,
    /(?:dm\s+me|message\s+me|text\s+me|contact\s+me)\b.{0,40}\+?\d{5,}/i,
  ];

  // ── AI-comment patterns — 2+ hits flags a comment as AI ──────────────────
  // These target generic, template-like positivity that real humans rarely use
  const AI_COMMENT_PATTERNS = [
    /(?:great|excellent|amazing|fantastic|wonderful)\s+(?:video|content|explanation|tutorial|work)/i,
    /(?:very|so|really|extremely)\s+(?:helpful|informative|educational|insightful|valuable)/i,
    /keep\s+(?:up\s+the\s+)?(?:great|good|amazing|excellent|wonderful)\s+work/i,
    /(?:looking\s+forward\s+to|can'?t\s+wait\s+for)\s+(?:more|your\s+next)/i,
    /well[\s-](?:explained|presented|structured|made|done)/i,
    /thank\s+you\s+for\s+(?:sharing|this\s+(?:amazing|wonderful|great|helpful)|the\s+(?:amazing|wonderful|helpful))/i,
    /this\s+(?:really|truly|definitely|certainly)\s+(?:helped|clarified|answered)/i,
    /(?:valuable|insightful|educational)\s+(?:content|video|information|insights?)/i,
    /I\s+(?:really\s+)?(?:enjoyed|loved|appreciated)\s+(?:this|the)\s+(?:video|content)/i,
    /(?:just\s+)?subscribed[!.]*\s*(?:keep|love|great|amazing)/i,
    /this\s+is\s+(?:exactly|just)\s+what\s+I\s+(?:needed|was\s+looking\s+for)/i,
    /(?:I\s+)?(?:learned|gained)\s+(?:a\s+lot|so\s+much)\s+from/i,
  ];
  const AI_COMMENT_THRESHOLD = 2;

  // ── AI video keyword lists ─────────────────────────────────────────────────
  const AI_TITLE_KW = [
    'ai generated', 'made with ai', 'created by ai', 'ai created',
    'midjourney', 'stable diffusion', 'dall-e', 'dalle', 'sora',
    'runway ml', 'pika labs', 'kling ai', 'hailuo ai', 'veo 2',
    'ai art', 'ai video', 'ai animation', 'ai film',
    '#aiart', '#aianimation', '#aigenerated', '#aifilm',
    'text to video', 'text-to-video', 'generated by ai',
    'ai short', 'ai narrator', 'ai voice', 'ai story', 'ai narrator',
  ];
  const AI_CHANNEL_KW = [
    'ai generated', 'ai channel', 'ai animation', 'ai studio',
    'ai art channel', 'ai shorts', 'ai films', 'ai stories',
    'aigenerated', 'aianimation',
  ];

  // ── Runtime state ──────────────────────────────────────────────────────────
  let flaggedChannels = new Set();
  let modules = { comments: true, videos: true, shorts: true };

  function loadSettings() {
    chrome.storage.local.get(['flaggedChannels', 'moduleState'], (r) => {
      if (r.flaggedChannels) flaggedChannels = new Set(r.flaggedChannels.map(c => c.toLowerCase()));
      if (r.moduleState) modules = { ...modules, ...r.moduleState };
    });
  }
  chrome.storage.onChanged.addListener((changes) => {
    if (changes.flaggedChannels)
      flaggedChannels = new Set((changes.flaggedChannels.newValue || []).map(c => c.toLowerCase()));
    if (changes.moduleState)
      modules = { ...modules, ...changes.moduleState.newValue };
  });

  // ── Utilities ──────────────────────────────────────────────────────────────
  const lower = s => (s || '').trim().toLowerCase();

  const BADGE_TITLES = {
    ok:    'Appears to be human-made content',
    ai:    'May contain AI-generated content',
    bot:   'Detected bot or spam pattern',
    human: 'Appears to be written by a real person',
  };

  function makeBadge(status) {
    const el = document.createElement('span');
    el.className = `ytabd-badge ytabd-${status}`;
    el.textContent = status.toUpperCase();
    el.title = BADGE_TITLES[status] || '';
    return el;
  }

  // ── Analysis: comments ─────────────────────────────────────────────────────
  function analyzeComment(text) {
    if (!text || text.length < 4) return 'human';

    for (const p of BOT_PATTERNS) {
      if (p.test(text)) return 'bot';
    }

    let score = 0;
    for (const p of AI_COMMENT_PATTERNS) {
      if (p.test(text) && ++score >= AI_COMMENT_THRESHOLD) return 'ai';
    }

    return 'human';
  }

  // ── Analysis: video content ────────────────────────────────────────────────
  function analyzeVideo(title, channel) {
    const t = lower(title);
    const c = lower(channel);
    if (flaggedChannels.has(c)) return 'ai';
    for (const kw of AI_TITLE_KW)   if (t.includes(kw)) return 'ai';
    for (const kw of AI_CHANNEL_KW) if (c.includes(kw)) return 'ai';
    return 'ok';
  }

  // ── Module 1: Comments ─────────────────────────────────────────────────────
  function scanComments() {
    if (!modules.comments) return;

    document.querySelectorAll(COMMENT_SEL).forEach(el => {
      const textEl = el.querySelector(
        '#content-text, #comment-content, yt-attributed-string'
      );
      const timeEl = el.querySelector(
        '#published-time-text, .published-time-text'
      );
      if (!textEl || !timeEl) return;

      const status = analyzeComment(textEl.textContent);
      el.setAttribute(ATTR, status);

      if (!timeEl.querySelector('.ytabd-badge')) {
        timeEl.appendChild(makeBadge(status));
      }
    });
  }

  // ── Module 2: Current watch-page video ────────────────────────────────────
  function scanWatchPage() {
    if (!modules.videos) return;

    // Multiple fallback selectors for the main video title h1
    const titleEl = document.querySelector(
      'ytd-watch-metadata h1 yt-formatted-string, ' +
      '#above-the-fold #title h1 yt-formatted-string, ' +
      'h1.ytd-watch-metadata yt-formatted-string'
    );
    if (!titleEl) return;

    const h1 = titleEl.closest('h1') || titleEl;
    if (h1.hasAttribute(ATTR)) return;

    const channelEl = document.querySelector(
      'ytd-watch-metadata ytd-channel-name yt-formatted-string, ' +
      '#owner ytd-channel-name yt-formatted-string, ' +
      '#channel-name yt-formatted-string'
    );

    const status = analyzeVideo(titleEl.textContent, channelEl?.textContent);
    h1.setAttribute(ATTR, status);

    if (!h1.querySelector('.ytabd-badge')) {
      const badge = makeBadge(status);
      badge.classList.add('ytabd-video-title');
      h1.appendChild(badge);
    }
  }

  // ── Module 4: Shorts viewer + Shorts shelf cards ──────────────────────────
  function scanShorts() {
    if (!modules.shorts) return;

    document.querySelectorAll(REEL_SEL).forEach(el => {
      // The channel bar holds the channel name + subscribe button
      const channelBar = el.querySelector('yt-reel-channel-bar-view-model');
      if (!channelBar) return;

      const subscribeEl = channelBar.querySelector(
        'yt-subscribe-button-view-model, ytd-subscribe-button-renderer, #subscribe-button'
      );
      if (!subscribeEl) return; // not rendered yet — will rescan on next mutation

      const titleEl = el.querySelector(
        'yt-shorts-video-title-view-model, #shorts-title, h2.title, ' +
        '[class*="title"] yt-formatted-string, yt-formatted-string.title'
      );
      const channelEl = channelBar.querySelector(
        'yt-dynamic-text-view-model, ytd-channel-name yt-formatted-string, ' +
        'yt-dynamic-sizing-formatted-string'
      );

      const status = analyzeVideo(titleEl?.textContent, channelEl?.textContent);
      el.setAttribute(ATTR, status);

      if (!channelBar.querySelector('.ytabd-badge')) {
        // subscribe's parent is a flex-column (name above subscribe).
        // Force it to flex-row so badge sits inline to the right of subscribe.
        const subscribeParent = subscribeEl.parentElement;
        if (subscribeParent) {
          subscribeParent.classList.add('ytabd-short-row');
        }
        const badge = makeBadge(status);
        badge.classList.add('ytabd-shorts');
        subscribeEl.insertAdjacentElement('afterend', badge);
      }
    });
  }

  // ── Master scan ────────────────────────────────────────────────────────────
  function scanAll() {
    const url = location.href;

    if (url.includes('/watch')) scanWatchPage();
    scanComments();
    scanShorts();
  }

  // ── MutationObserver — react to YouTube's dynamic DOM ────────────────────
  let timer = null;
  const observer = new MutationObserver(mutations => {
    for (const m of mutations) {
      if (m.addedNodes.length) {
        clearTimeout(timer);
        timer = setTimeout(scanAll, 280);
        return;
      }
    }
  });

  // YouTube SPA navigation — clear all markers and re-scan the new page
  window.addEventListener('yt-navigate-finish', () => {
    document.querySelectorAll(`[${ATTR}]`).forEach(el => el.removeAttribute(ATTR));
    document.querySelectorAll('.ytabd-badge').forEach(el => el.remove());
    clearTimeout(timer);
    timer = setTimeout(scanAll, 400);
  });

  // ── Init ───────────────────────────────────────────────────────────────────
  function init() {
    loadSettings();
    observer.observe(document.documentElement, { childList: true, subtree: true });
    scanAll();
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
